services:
  php-fpm:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    image: motviet
    restart: always
    volumes:
      - app_data:/app
  nginx:
    image: nginx
    restart: always
    ports:
      - 9999:80
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - app_data:/app
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php-fpm
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: doan_banquanao
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
 app_data: